// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/jordanlanch/docucenter-test/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CustomerUsecase is an autogenerated mock type for the CustomerUsecase type
type CustomerUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *CustomerUsecase) Create(c *domain.Customer) (*domain.Customer, error) {
	ret := _m.Called(c)

	var r0 *domain.Customer
	if rf, ok := ret.Get(0).(func(*domain.Customer) *domain.Customer); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Customer) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *CustomerUsecase) GetByID(id uuid.UUID) (*domain.Customer, error) {
	ret := _m.Called(id)

	var r0 *domain.Customer
	if rf, ok := ret.Get(0).(func(uuid.UUID) *domain.Customer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMany provides a mock function with given fields: pagination
func (_m *CustomerUsecase) GetMany(pagination *domain.Pagination) ([]*domain.Customer, error) {
	ret := _m.Called(pagination)

	var r0 []*domain.Customer
	if rf, ok := ret.Get(0).(func(*domain.Pagination) []*domain.Customer); ok {
		r0 = rf(pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Pagination) error); ok {
		r1 = rf(pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Modify provides a mock function with given fields: c, id
func (_m *CustomerUsecase) Modify(c *domain.Customer, id uuid.UUID) (*domain.Customer, error) {
	ret := _m.Called(c, id)

	var r0 *domain.Customer
	if rf, ok := ret.Get(0).(func(*domain.Customer, uuid.UUID) *domain.Customer); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Customer, uuid.UUID) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: id
func (_m *CustomerUsecase) Remove(id uuid.UUID) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCustomerUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewCustomerUsecase creates a new instance of CustomerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCustomerUsecase(t mockConstructorTestingTNewCustomerUsecase) *CustomerUsecase {
	mock := &CustomerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
