version: '3.5'

services:

  db-docucenter-test:
    image: postgres:14.0-alpine
    ports:
      - "5469:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: docucenter-test-db-test
